apiVersion: v1
kind: Namespace
metadata:
  name: sample-app

---

# Deployment for the fastAPI app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-app
  template:
    metadata:
      labels:
        app: fast-app
    spec:
      containers:
        - name: fast-app
          image: APP_IMAGE_NAME:BUILD_VERSION
          ports:
            - containerPort: 8080
---
# Service for the fastAPI app
apiVersion: v1
kind: Service
metadata:
  name: fast-nodeport
  namespace: sample-app
spec:
  selector:
    app: fast-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
